# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2021-09-28.json
openapi: 3.0.2
info:
  version: 0.0.1
  title: Gortener openapi spec
paths:
  /urls:
    post:
      tags:
        - url
      summary: create an url to be shortened
      operationId: addURL
      responses:
        '201':
          description: url shortened successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URL'
        '500':
          description: error while creating a shortened url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    URL:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          example: https://google.com/url/to/be/shortened
        shortened-url:
          type: string
          example: https://gortner.com/shortened-url
    error:
      type: object
      properties:
        message:
          type: string
