version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORK:-changeme}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db: